run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocritic
    - revive

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  gosec:
    excludes:
      - G404 # Random number generation (not security critical for this app)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - gocritic
