version: '3.8'

services:
  skywalking-transformer:
    image: ghcr.io/codifinary/skywalking-transformer:latest
    container_name: skywalking-transformer
    ports:
      - "8081:8081"
    environment:
      - CODEXRAY_COLLECTOR_URL=http://${BASE_URL}/v1/traces
      - CODEXRAY_RECEIVER_PORT=8081
      - CODEXRAY_WORKERS=8
      - CODEXRAY_QUEUE_SIZE=100000
      - CODEXRAY_BATCH_SIZE=500
      - CODEXRAY_BATCH_FLUSH_MS=200
      - CODEXRAY_HTTP_TIMEOUT_MS=10000
      - CODEXRAY_SHUTDOWN_TIMEOUT_MS=15000
      - CODEXRAY_QUEUE_DROP_ON_FULL=false
    restart: unless-stopped
