// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v3/segments": {
            "post": {
                "description": "Receives SkyWalking segments, converts to OTLP, and enqueues for async forwarding",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SkyWalking"
                ],
                "summary": "Collect SkyWalking segments",
                "parameters": [
                    {
                        "description": "SkyWalking Trace Segments",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/skywalking.TraceSegment"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "skywalking.Log": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/skywalking.Tag"
                    }
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "skywalking.Reference": {
            "type": "object",
            "properties": {
                "headers": {
                    "type": "string"
                },
                "traceId": {
                    "type": "string"
                }
            }
        },
        "skywalking.Span": {
            "type": "object",
            "properties": {
                "componentId": {
                    "type": "integer"
                },
                "endTime": {
                    "type": "integer"
                },
                "isError": {
                    "type": "boolean"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/skywalking.Log"
                    }
                },
                "methodName": {
                    "description": "nullable",
                    "type": "string"
                },
                "operationName": {
                    "type": "string"
                },
                "parentSpanId": {
                    "type": "integer"
                },
                "peer": {
                    "type": "string"
                },
                "references": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/skywalking.Reference"
                    }
                },
                "skipAnlysis": {
                    "type": "boolean"
                },
                "spanId": {
                    "type": "integer"
                },
                "spanLayer": {
                    "type": "string"
                },
                "spanType": {
                    "type": "string"
                },
                "startTime": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/skywalking.Tag"
                    }
                }
            }
        },
        "skywalking.Tag": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "skywalking.TraceSegment": {
            "type": "object",
            "properties": {
                "isSizeLimited": {
                    "type": "boolean"
                },
                "service": {
                    "type": "string"
                },
                "serviceInstance": {
                    "type": "string"
                },
                "spans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/skywalking.Span"
                    }
                },
                "traceId": {
                    "type": "string"
                },
                "traceSegmentId": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SkyWalking Collector API Example",
	Description:      "This is an example API to receive SkyWalking agent payloads.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
